/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ctbriekiwinepwlbnfvb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0YnJpZWtpd2luZXB3bGJuZnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMDc0OTcsImV4cCI6MjA3NDg4MzQ5N30.cBR7KvuPNc_-VGr456-qihq57mu2PEDCvEdf1Wmj9AI"